defmodule Storybook.UI.PixQR do
  use PhoenixStorybook.Story, :component

  def function, do: &RolezinhoWeb.Components.UI.PixQR.pix_qr/1

  def template do
    """
    <div class="rounded-cta bg-surface p-3.5 max-w-[358px]" psb-code-hidden>
      <.psb-variation/>
    </div>
    """
  end

  # Generated by our own code from a sample key, with no user-supplied fragment —
  # which is what makes it safe for the component to render with raw/1.
  defp sample_svg do
    Rolezinho.Pix.qr_svg("+5591984933238", name: "MARCIA", city: "BELEM", width: 148)
  end

  def variations do
    [
      %Variation{
        id: :with_amount,
        description:
          "Exists because copying a key fails often in person. The app never confirms the " <>
            "payment: the QR only carries the payee's data into the bank app.",
        attributes: %{
          svg: sample_svg(),
          amount: "R$ 15",
          payee: "Marcia",
          pix_key: "91984933238"
        }
      },
      %Variation{
        id: :key_only,
        description: "A free event, or one where the amount is settled elsewhere.",
        attributes: %{
          svg: sample_svg(),
          pix_key: "91984933238",
          hint: nil
        }
      }
    ]
  end
end
