import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :rolezinho, RolezinhoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :rolezinho, RolezinhoWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Mark the session cookie as Secure in production. Read by the endpoint at
# compile time (`Application.compile_env(:rolezinho, :session_secure, ...)`),
# so this has to live in a compile-time config file, not `runtime.exs`.
# Combined with the compile-time `force_ssl` above and Fly.io's HTTPS
# proxy, the cookie is only ever set/sent over HTTPS anyway; the flag
# just tells Safari to trust it accordingly across OAuth redirects.
config :rolezinho, :session_secure, true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
