defmodule RolezinhoWeb.Components.UI.PixQR do
  @moduledoc """
  The event's Pix QR code, next to the amount and the payee.

  Exists because copying a key fails often in person — a wrong paste, a key read
  aloud across a court. The app never confirms the payment: the QR only carries
  the payee's data into the bank app, and marking it paid stays a declaration by
  whoever paid.

  The SVG comes from `Rolezinho.Pix.qr_svg/2`, generated by our own code with no
  user-supplied fragment, which is what makes it safe to render with `raw/1`.
  """
  use Phoenix.Component

  import Phoenix.HTML, only: [raw: 1]

  @doc """
  Renders the QR block.

  ## Examples

      <.pix_qr svg={@qr_svg} amount="R$ 15" payee="Marcia" pix_key="91984933238" />
  """
  attr :svg, :string, required: true, doc: "SVG markup from Rolezinho.Pix.qr_svg/2"
  attr :amount, :string, default: nil
  attr :payee, :string, default: nil
  attr :pix_key, :string, default: nil

  attr :copy_value, :string,
    default: nil,
    doc: "the canonical key, shown in a readonly field for manual copying"

  attr :hint, :string, default: "Pix copia e cola com o valor já preenchido."
  attr :class, :any, default: nil

  slot :action, doc: "the copy button, rendered under the hint"

  def pix_qr(assigns) do
    ~H"""
    <div class={["flex items-center gap-3", @class]}>
      <div class="size-[74px] shrink-0 rounded-row border border-hairline bg-base-100 p-2 [&>svg]:size-full">
        {raw(@svg)}
      </div>
      <div class="min-w-0 flex-1">
        <div :if={@amount || @payee} class="truncate text-sm font-extrabold">
          {[@amount, @payee] |> Enum.reject(&is_nil/1) |> Enum.join(" · ")}
        </div>
        <div :if={@pix_key} class="mt-0.5 truncate font-mono text-[11px] text-muted">
          {@pix_key}
        </div>
        <p :if={@hint} class="mt-1 text-[11px] leading-snug text-muted">{@hint}</p>
        <!-- Readonly, not disabled: a disabled field cannot be focused or
             selected, which is the whole point of showing the key here. The
             canonical key is what a bank app accepts, so it is what gets
             copied — never the formatted version shown above. -->
        <input
          :if={@copy_value}
          type="text"
          readonly
          value={@copy_value}
          aria-label="Chave Pix para copiar"
          class="mt-2 w-full select-all rounded-row border border-hairline bg-canvas px-2 py-1.5 font-mono text-[11px] text-ink focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-accent"
        />
        <div :if={@action != []} class="mt-2">{render_slot(@action)}</div>
      </div>
    </div>
    """
  end
end
