defmodule RolezinhoWeb.Components.UI.SharePreview do
  @moduledoc """
  The event's text, monospaced, exactly as it will be pasted into the group.

  This is a preview of one of the three outputs (see `DESIGN.md`, section 7): the
  text is generated by `Rolezinho.Event`, and what is shown here must be
  character-for-character what gets copied — a preview that "prettifies" the text
  is a lie about what lands in the chat.

  The text is rendered as content, never as markup.
  """
  use Phoenix.Component

  @doc """
  Renders the share preview.

  ## Examples

      <.share_preview text={Rolezinho.Event.to_text(@event)} />
  """
  attr :text, :string, required: true
  attr :class, :any, default: nil

  # `bg-base-100` (not `bg-white`) so the surface inverts under
  # `[data-theme="dark"]` — otherwise the near-white `text-ink` used in
  # dark mode paints over a stubbornly white background and the text
  # becomes invisible.
  def share_preview(assigns) do
    ~H"""
    <pre class={[
      "overflow-x-auto rounded-cta border border-ink/8 bg-base-100 p-3",
      "font-mono text-[10px] leading-relaxed whitespace-pre-wrap text-ink",
      @class
    ]}><%= @text %></pre>
    """
  end
end
