defmodule RolezinhoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :rolezinho

  # The session lives in a signed cookie — contents readable, not
  # tampered with. Set :encryption_salt if you would also like to encrypt it.
  #
  # `max_age` and `secure` are here to keep Safari mobile happy across the
  # OAuth roundtrip (app → github.com → app):
  #
  #   * `max_age` — without it, the cookie is a Session cookie, which
  #     mobile Safari (ITP) drops aggressively when the tab is
  #     backgrounded or the browser is memory-pressured. That was the
  #     visible "kept getting disconnected from login" symptom: the
  #     Ueberauth state cookie was gone by the time GitHub redirected
  #     back, so the callback failed and the user was signed out again.
  #     60 days is long enough to survive any real-world OAuth flow and
  #     the app's own usage patterns without being effectively permanent.
  #
  #   * `secure` — in prod (`force_ssl` on, HTTPS-only) the cookie should
  #     be marked Secure so Safari treats it as first-class; without the
  #     flag Safari's SameSite=Lax handling can be inconsistent for
  #     redirects arriving from a third-party origin. Read at compile
  #     time from `:session_secure` so dev (HTTP on localhost) keeps
  #     working without a warning.
  @session_options [
    store: :cookie,
    key: "_rolezinho_key",
    signing_salt: "sAaZCF8t",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 60,
    secure: Application.compile_env(:rolezinho, :session_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :rolezinho,
    gzip: not code_reloading?,
    only: RolezinhoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :rolezinho
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RolezinhoWeb.Plugs.TxtRewrite
  plug RolezinhoWeb.Router
end
